#!/bin/bash
# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

# Builds an RV64 Ubuntu rootfs.

set -euo pipefail
set -x

d=$(dirname "${BASH_SOURCE[0]}")
distro=noble

packages=(
        arping
        binutils
        elfutils
        ethtool
        fsverity
        iproute2
        iptables
        jq
        keyutils
        libasound2t64
        libcap2
        libelf1
        libnuma1
        net-tools
        netsniff-ng
        openssl
        psmisc
        smcroute
        socat
        strace
        systemd-sysv
        tcpdump
        udev
        uuid-runtime
        zlib1g
)

tuxrun=$1

if [[ -n $tuxrun ]]; then
    packages+=(
        gdb
        libnuma-dev
        libfuse-dev
        fuse3
        genisoimage
        xorriso
        squashfs-tools
        libubsan1
    )

    packages+=(
        acl
        adduser
        apt
        attr
        autoconf
        automake
        autotools-dev
        base-files
        base-passwd
        bash
        bc
        binutils-common
        binutils-riscv64-linux-gnu
        bsdutils
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        cpp
        cpp-12
        dash
        dbench
        dbus
        dbus-bin
        dbus-daemon
        dbus-session-bus-common
        dbus-system-bus-common
        dbus-user-session
        debconf
        debian-archive-keyring
        debianutils
        diffutils
        dmeventd
        dmsetup
        dpkg
        dump
        e2fsprogs
        exfatprogs
        f2fs-tools
        file
        findutils
        fio
        gawk
        gcc
        gcc-12
        gcc-12-base
        git
        git-man
        gpgv
        grep
        gzip
        hostname
        indent
        init-system-helpers
        initramfs-tools-core
        isc-dhcp-client
        jfsutils
        klibc-utils
        kmod
        libacl1
        libacl1-dev
        libaio-dev
        libapparmor1
        libapt-pkg6.0
        libargon2-1
        libasan8
        libatomic1
        libattr1
        libattr1-dev
        libaudit-common
        libaudit1
        libbinutils
        libblkid1
        libboost-iostreams1.74.0
        libboost-thread1.74.0
        libbpf1
        libbrotli1
        libbsd0
        libbz2-1.0
        libc-bin
        libc-dev-bin
        libc6
        libc6-dev
        libcap-dev
        libcap-ng0
        libcap2-bin
        libcc1-0
        libcmap4
        libcom-err2
        libcorosync-common4
        libcrypt-dev
        libcrypt1
        libcryptsetup12
        libctf-nobfd0
        libctf0
        libcurl3-gnutls
        libdaxctl1
        libdb5.3
        libdbus-1-3
        libdebconfclient0
        libdevmapper-event1.02.1
        libdevmapper1.02.1
        libdlm3
        libedit2
        liberror-perl
        libexpat1
        libext2fs2
        libfdisk1
        libffi8
        libfmt9
        libgcc-12-dev
        libgcc-s1
        libgcrypt20
        libgdbm-compat4
        libgdbm-dev
        libgdbm6
        libgfapi0
        libgfrpc0
        libgfxdr0
        libglib2.0-0
        libglusterfs0
        libgmp10
        libgnutls30
        libgomp1
        libgpg-error0
        libgssapi-krb5-2
        libhogweed6
        libibverbs1
        libicu-dev
        libidn2-0
        libinih1
        libip4tc2
        libisl23
        libitm1
        libjansson4
        libjson-c5
        libk5crypto3
        libkeyutils1
        libklibc
        libkmod2
        libkrb5-3
        libkrb5support0
        liblsan0
        liblua5.3-0
        liblvm2cmd2.03
        liblz4-1
        liblzma5
        liblzo2-2
        libmagic-mgc
        libmagic1
        libmd0
        libmnl0
        libmount1
        libmpc3
        libmpfr6
        libnbd0
        libncurses6
        libncursesw6
        libndctl6
        libnettle8
        libnghttp2-14
        libnl-3-200
        libnl-genl-3-200
        libnl-route-3-200
        libnsl-dev
        libnsl2
        libp11-kit0
        libpam-modules
        libpam-modules-bin
        libpam-runtime
        libpam-systemd
        libpam0g
        libpcap0.8
        libpcre2-8-0
        libperl5.38
        libpmem1
        libpmemblk1
        libpopt0
        libpsl5
        libpython3-stdlib
        libpython3.12-minimal
        libpython3.12-stdlib
        libqb100
        librados2
        librbd1
        librdmacm1
        libreadline8
        librtmp1
        libsasl2-2
        libsasl2-modules-db
        libseccomp2
        libselinux1
        libsemanage-common
        libsemanage2
        libsepol2
        libsigsegv2
        libsmartcols1
        libsqlite3-0
        libss2
        libssh2-1
        libssl3
        libstdc++6
        libsystemd-shared
        libsystemd0
        libtasn1-6
        libtinfo6
        libtirpc-common
        libtirpc-dev
        libtirpc3
        libtool
        libtool-bin
        libtsan2
        libudev1
        libunistring-dev
        libunwind8
        liburcu8
        liburing-dev
        liburing2
        libuuid1
        libwrap0
        libxml2
        libxtables12
        libxxhash0
        libzstd1
        linux-libc-dev
        login
        logsave
        lvm2
        lz4
        m4
        make
        mawk
        media-types
        mount
        ncat
        ncurses-base
        ncurses-bin
        nilfs-tools
        ocfs2-tools
        passwd
        perl
        perl-base
        perl-modules-5.38
        python3
        python3-minimal
        python3.12
        python3.12-minimal
        quota
        readline-common
        rpcsvc-proto
        sed
        systemd
        sysvinit-utils
        tar
        tzdata
        udftools
        usr-is-merged
        util-linux
        util-linux-extra
        uuid-dev
        xfsdump
        xfslibs-dev
        xfsprogs
        xz-utils
    )
fi

packages=$(IFS=, && echo "${packages[*]}")

name="rootfs_rv64_ubuntu_$(date +%Y.%m.%d).tar"

mmdebstrap --include="$packages" \
           --architecture=riscv64 \
           --components="main restricted multiverse universe" \
           --customize-hook=$d/systemd-debian-customize-hook.sh \
           --skip=cleanup/reproducible \
           "${distro}" \
           "${name}"

if [[ -n $tuxrun ]]; then
    mkdir -p tmp
    tar -C tmp -xvf ${name}
    mkfs.ext4 -d tmp $name.ext4 16g
else
    zstd --rm -T0 --ultra -20 $name
fi
